let staticbox = document.getElementById('static')
let staticinfo = ''
const urlParams = new URLSearchParams(window.location.search)
let boardId = urlParams.get('id')
let name = urlParams.get('name')
let userid = urlParams.get('userid')
let jc = urlParams.get('jc')
staticinfo = 'Board ID: ' + boardId + ' || Join Code: ' + jc + ' || Username: ' + name + ' || User ID: ' + userid
staticbox.innerHTML = staticinfo